services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    networks:
      - kong-net
    ports:
      - "5432:5432"

  kong-migrations:
    image: kong/kong-gateway:3.8.0.0
    container_name: kong-migrations
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kongpass
    networks:
      - kong-net
    command: "kong migrations bootstrap"

  kong-gateway:
    image: kong/kong-gateway:3.8.0.0
    container_name: kong-gateway
    depends_on:
      - kong-database
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_HOST: 0.0.0.0
      KONG_ADMIN_GUI_PORT: 8002
      KONG_PLUGINS: bundled,custom-aggregator
      KONG_LUA_PACKAGE_PATH: "/usr/local/share/lua/5.1/?.lua;;"
    volumes:
      - ./custom-aggregator:/usr/local/share/lua/5.1/kong/plugins/custom-aggregator
    networks:
      - kong-net
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"

  healthcare:
    build:
      context: ./healthcare
    container_name: healthcare
    volumes:
      - ./healthcare:/app
      - /app/node_modules
    networks:
      - kong-net
    ports:
      - "3000:3000"

  grand-oak:
    build:
      context: ./grand-oak
    container_name: grand-oak
    volumes:
      - ./grand-oak:/app
    networks:
      - kong-net
    ports:
      - "8081:8080"

  pine-valley:
    build:
      context: ./PineValleyService
    container_name: pine-valley
    networks:
      - kong-net
    ports:
      - "8082:8080"

  willow-gardens:
    build:
      context: ./willow-gardens
    container_name: willow-gardens
    volumes:
      - ./willow-gardens:/app
    networks:
      - kong-net
    ports:
      - "8083:8080"

networks:
  kong-net:
    driver: bridge
